worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    # Define o grupo de servidores Flask (o Docker vai balancear entre as réplicas)
    upstream backend_servers {
        server backend:5000;
    }

    server {
        listen 80;
        server_name localhost;

        # 1. Entrega a interface do jogo (React)
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        # 2. Proxy Reverso: Captura pedidos para /api/ e envia para o Python
        location /api/ {
            proxy_pass http://backend_servers/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}